(()=>{'use strict';const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],T=Math.PI*2;
const JEWELS=[
 ['和田白玉','#eee8d8','#8f866e','green','坤'],['羊脂白玉','#fff9ed','#c9b990','green','乾'],['冰种翡翠','#dceff1','#77969a','green','坎'],['帝王绿','#087b42','#063f27','green','震'],['苹果绿翡翠','#64bc46','#2f762c','green','巽'],['竹叶青玉','#758b64','#374937','green','艮'],
 ['紫罗兰翡翠','#b5a4d9','#665884','purple','兑'],['紫水晶','#7d54a5','#3c285b','purple','离'],['粉水晶','#efb4bf','#a96877','pink','兑'],['桃花玉','#e7a897','#9a6558','pink','坤'],['红翡翠','#c91847','#790c29','dark','离'],['南红玛瑙','#bc3c12','#6d210d','dark','离'],
 ['海蓝宝','#b7deea','#56889a','blue','坎'],['蓝宝晶','#1748b8','#102968','blue','坎'],['绿松石','#45b9c1','#287177','blue','震'],['青金石','#183b9d','#10245e','blue','艮'],['蜜蜡琥珀','#d98b17','#824a08','dark','离'],['黄玉','#e9b93f','#956f1e','dark','艮'],
 ['黑曜石','#15171a','#020305','dark','坎'],['墨翠','#102b24','#061713','dark','坤'],['烟晶','#66534a','#30241f','dark','坤'],['虎眼石','#a9660c','#5b3205','dark','艮'],['青玉','#a8c7ad','#617c67','green','震'],['岫玉','#8fae8e','#4d684c','green','坤'],
 ['月光石','#dce6f5','#8098bd','blue','乾'],['欧泊','#eee8cf','#afa777','blue','兑'],['白水晶','#edf4f6','#91a1a7','blue','乾'],['金发晶','#ad8b56','#634924','dark','离'],['冰粉翡翠','#e4bac5','#9c7280','pink','兑'],['碧玺','#9b4b4a','#5c2c33','dark','巽']
].map((v,i)=>({id:i,name:v[0],color:v[1],dark:v[2],scene:v[3],gua:v[4],difficulty:i+1,asset:`assets/materials/ring-${String(i+1).padStart(2,'0')}.png`}));
const SCENES={pink:'assets/peach-jade-board-v3.png',green:'assets/scene-green-v5.png',purple:'assets/scene-purple-v5.png',blue:'assets/scene-blue-v5.png',dark:'assets/scene-dark-v5.png'};
const GUA=[['乾','西北'],['兑','正西'],['离','正南'],['震','正东'],['巽','东南'],['坎','正北'],['艮','东北'],['坤','西南']];
const BLESSINGS=['玉润心和，万事顺遂','白璧无瑕，守正得福','冰心澄澈，静则生慧','翠色长青，福泽绵延','春意盈怀，生机自来','竹报平安，节节清宁','紫气东来，祥光入怀','星辉映玉，明心见性','桃颜含瑞，缘起花开','和气致祥，玉缘圆满','赤玉呈瑞，鸿运初开','丹霞焕彩，喜乐长安','海纳清辉，心宽福至','碧空澄明，前路光华','松石长青，安宁相伴','金星入玉，所愿皆成','蜜意流光，福暖人间','金玉满堂，吉庆有余','玄光守静，否极泰来','墨翠含章，厚德载福','烟岚舒卷，顺势而安','虎耀生威，勇而有节','青玉温润，君子守中','岫色含春，百福自集','月华流照，清宁长伴','火彩生辉，万象更新','水晶澄心，所行无碍','金丝纳福，光明常随','粉玉结缘，和美圆融','碧玺呈祥，福慧双增'];
const WISDOM={乾:'天行健，君子以自强不息',坤:'地势坤，君子以厚德载物',震:'雷动而生，守正以待其时',巽:'随风而入，柔顺亦能致远',坎:'临险不惧，持中自有通途',离:'明而不耀，照见内心本真',艮:'知止而定，静中方能生慧',兑:'和悦相感，诚心自有吉应'};
const state={level:0,moves:0,hints:3,start:0,sound:localStorage.getItem('yh-sound')!=='false',easy:localStorage.getItem('yh-easy')!=='false',completed:new Set(JSON.parse(localStorage.getItem('yh-completed-v5')||'[]')),rings:[],clasps:[],drag:null};
const c=$('#board'),g=c.getContext('2d'),materialSprites=JEWELS.map(j=>{let img=new Image();img.src=j.asset;return img});
function setScreen(id){$$('.screen').forEach(s=>s.classList.remove('active'));$('#'+id).classList.add('active')}
function save(){localStorage.setItem('yh-completed-v5',JSON.stringify([...state.completed]));localStorage.setItem('yh-last-v5',String(state.level))}function last(){return Math.max(0,Math.min(29,Number(localStorage.getItem('yh-last-v5')||0)))}
function unlocked(){return true}
function buildHome(){let j=JEWELS[last()];$('#lastLabel').textContent=`第${toCN(j.id+1)}境 · ${j.name}`}
function buildTreasury(){let box=$('#jewelGrid');box.innerHTML='';JEWELS.forEach((j,i)=>{let b=document.createElement('button'),done=state.completed.has(i);b.className='jewel-card';b.style.setProperty('--jewel',j.color);b.innerHTML=`<span class="status">${done?'已收入':'点击进入'}</span><small>第${toCN(i+1)}境 · 难度 ${String(i+1).padStart(2,'0')}</small><strong>${j.name}</strong><div class="jewel-mini" style="--material:url('${j.asset}')"></div><em>${j.gua}象 · ${i<5?'初识榫理':i<15?'阴阳互扣':i<25?'多重牵制':'万象归环'}</em>`;b.onclick=()=>openGame(i);box.appendChild(b)});$('#totalDone').textContent=state.completed.size}
function toCN(n){const a=['零','一','二','三','四','五','六','七','八','九','十'];if(n<=10)return a[n];if(n<20)return'十'+(n%10?a[n%10]:'');if(n<30)return'二十'+(n%10?a[n%10]:'');return'三十'}
function openGame(i){state.level=i;let j=JEWELS[i];$('#levelNo').textContent=`第${toCN(i+1)}境 · 难度 ${String(i+1).padStart(2,'0')}`;$('#jewelName').textContent=j.name;$('#blessingText').textContent=BLESSINGS[i];$('#wisdomText').textContent=WISDOM[j.gua];$('#gameScreen').style.backgroundImage=`url('${SCENES[j.scene]}')`;state.moves=0;state.hints=3;state.start=Date.now();$('#moves').textContent=0;$('#hints').textContent=3;$('#moveGoal').textContent=`/ ${14+Math.floor(i/2)}`;$('#guide').classList.remove('hide');initPuzzle(i);updateOracle();save();setScreen('gameScreen');if(state.sound){let a=$('#bgm');a.volume=.13;a.play().catch(()=>{})}}
function coords(n){const maps={
 5:[[255,340],[465,340],[150,520],[360,520],[570,520]],
 6:[[255,260],[465,260],[255,470],[465,470],[255,680],[465,680]],
 7:[[255,290],[465,290],[150,465],[360,465],[570,465],[255,640],[465,640]],
 8:[[180,300],[360,300],[540,300],[270,460],[450,460],[180,620],[360,620],[540,620]],
 9:[[180,280],[360,280],[540,280],[180,460],[360,460],[540,460],[180,640],[360,640],[540,640]],
 10:[[180,300],[360,300],[540,300],[90,460],[270,460],[450,460],[630,460],[180,620],[360,620],[540,620]],
 11:[[180,280],[360,280],[540,280],[90,440],[270,440],[450,440],[630,440],[90,615],[270,615],[450,615],[630,615]],
 12:[[90,270],[270,270],[450,270],[630,270],[90,450],[270,450],[450,450],[630,450],[90,630],[270,630],[450,630],[630,630]]};return maps[n]}
function initPuzzle(level){let n=7,pts=[[260,310],[460,310],[160,485],[360,485],[560,485],[260,660],[460,660]],radius=96;state.rings=pts.map((p,i)=>({id:'r'+i,x:p[0],y:p[1],r:radius,rot:0,z:n-i,links:[],gone:false}));let pairs=[[0,1],[1,4],[4,6],[6,5],[5,2],[2,3]];if(level>=6)pairs.push([3,0]);if(level>=12)pairs.push([3,1]);if(level>=18)pairs.push([0,2]);let roots=level<6?2:1,claspStyle=level%4;state.clasps=pairs.map((pair,i)=>{let a=state.rings[pair[0]],b=state.rings[pair[1]],block=[];if(i>=roots)block.push('k'+Math.floor((i-roots)/2));if(level>=12&&i>roots+2){let extra='k'+Math.max(0,i-3);if(!block.includes(extra))block.push(extra)}if(level>=24&&i>5){let extra='k'+Math.max(0,i-5);if(!block.includes(extra))block.push(extra)}let obj={id:'k'+i,pair:[a.id,b.id],x:(a.x+b.x)/2,y:(a.y+b.y)/2,angle:Math.atan2(b.y-a.y,b.x-a.x),distance:Math.hypot(a.x-b.x,a.y-b.y),style:claspStyle,block,dir:level<4?0:(i%2?1:-1),gua:GUA[i%8],off:false};a.links.push(obj.id);b.links.push(obj.id);return obj});state.rings.forEach((r,i)=>{let angles=state.clasps.filter(k=>k.pair.includes(r.id)).map(k=>Math.atan2(k.y-r.y,k.x-r.x)),candidate=((level*43+i*67)%628)/100-3.14;for(let tries=0;tries<20;tries++){if(angles.every(a=>Math.abs(norm(candidate-a))>.92))break;candidate+=.61}r.rot=norm(candidate)});state.drag=null}
function ringBy(id){return state.rings.find(r=>r.id===id)}function exposed(k){return k.block.every(id=>state.clasps.find(q=>q.id===id)?.off)}function available(){return state.clasps.filter(k=>!k.off&&exposed(k))}function incident(r){return available().filter(k=>k.pair.includes(r.id))}function target(r,k){return Math.atan2(k.y-r.y,k.x-r.x)}
function drawRing(r){if(r.gone)return;let j=JEWELS[state.level],img=materialSprites[state.level],active=incident(r).length>0;g.save();g.translate(r.x,r.y);g.rotate(r.rot);g.lineCap='round';let arc=()=>{g.beginPath();g.arc(0,0,r.r,.36,T-.36)};g.shadowColor=active?'rgba(255,243,177,.95)':'rgba(42,15,28,.30)';g.shadowBlur=active?30:10;g.shadowOffsetY=7;g.strokeStyle=j.dark;g.globalAlpha=.18;g.lineWidth=r.r*.38;arc();g.stroke();g.shadowBlur=0;g.globalAlpha=1;if(img.complete&&img.naturalWidth){let s=r.r*2.28;g.globalAlpha=.99;g.drawImage(img,-s/2,-s/2,s,s)}g.strokeStyle='rgba(255,255,255,.56)';g.lineWidth=2.2;g.globalAlpha=.56;arc();g.stroke();g.restore()}
function drawClasp(k){if(k.off)return;let live=exposed(k),w=56,h=30;g.save();g.translate(k.x,k.y);g.rotate(k.angle);g.shadowColor=live?'#fff2a8':'#513019';g.shadowBlur=live?14:5;g.shadowOffsetY=2;let gold=g.createLinearGradient(-w/2,0,w/2,0);gold.addColorStop(0,'#7a4317');gold.addColorStop(.14,'#d9953d');gold.addColorStop(.33,'#fff0a4');gold.addColorStop(.52,'#c77b25');gold.addColorStop(.72,'#ffe89a');gold.addColorStop(1,'#814719');g.fillStyle=gold;g.strokeStyle='#fff0ad';g.lineWidth=1.6;g.beginPath();g.roundRect(-w/2,-h/2,w,h,7);g.fill();g.stroke();g.shadowBlur=0;g.strokeStyle='#7d461b99';g.lineWidth=1.2;g.beginPath();g.roundRect(-w/2+4,-h/2+4,w-8,h-8,4);g.stroke();g.strokeStyle='#fff7c6b5';g.beginPath();g.moveTo(-w/2+7,-h/2+6);g.lineTo(w/2-7,-h/2+6);g.stroke();let stones=k.style===0?[]:k.style===1?[0]:k.style===2?[-10,10]:[-12,0,12];if(!stones.length){g.strokeStyle='#8a4d1cbb';[-9,9].forEach(x=>{g.beginPath();g.moveTo(x,-7);g.lineTo(x,7);g.stroke()})}stones.forEach(x=>{g.save();g.translate(x,0);g.rotate(Math.PI/4);let d=g.createLinearGradient(-4,-4,4,4);d.addColorStop(0,'#91afbd');d.addColorStop(.4,'#ffffff');d.addColorStop(1,'#eadfae');g.fillStyle=d;g.strokeStyle='#fffde5';g.lineWidth=.7;g.fillRect(-2.8,-2.8,5.6,5.6);g.strokeRect(-2.8,-2.8,5.6,5.6);g.restore()});if(live){g.strokeStyle='#fff5b5c9';g.lineWidth=1.2;g.beginPath();g.roundRect(-w/2-3,-h/2-3,w+6,h+6,9);g.stroke()}g.restore()}
function frame(){if($('#gameScreen').classList.contains('active')){g.clearRect(0,0,c.width,c.height);[...state.rings].sort((a,b)=>a.z-b.z).forEach(drawRing);state.clasps.forEach(drawClasp)}requestAnimationFrame(frame)}
function point(e){let b=c.getBoundingClientRect();return{x:(e.clientX-b.left)*720/b.width,y:(e.clientY-b.top)*1040/b.height}}function norm(a){while(a>Math.PI)a-=T;while(a<-Math.PI)a+=T;return a}
function down(e){let p=point(e),r=[...state.rings].sort((a,b)=>b.z-a.z).find(r=>!r.gone&&Math.abs(Math.hypot(p.x-r.x,p.y-r.y)-r.r)<50);if(!r)return;if(!incident(r).length)return toast('此环仍被上层榫扣牵制');state.drag={r,last:Math.atan2(p.y-r.y,p.x-r.x),signed:0};c.setPointerCapture?.(e.pointerId);play('touch',.25);$('#guide').classList.add('hide');e.preventDefault()}
function move(e){if(!state.drag)return;let p=point(e),r=state.drag.r,a=Math.atan2(p.y-r.y,p.x-r.x),d=Math.max(-.28,Math.min(.28,norm(a-state.drag.last)));state.drag.last=a;state.drag.signed+=d;r.rot+=d;let tol=state.easy?.44:.31;for(let k of incident(r)){if(Math.abs(norm(r.rot-target(r,k)))<tol){if(k.dir&&Math.sign(state.drag.signed)!==k.dir){toast(k.dir>0?'阳扣须顺时针转动':'阴扣须逆时针转动');return}unlock(k,r);break}}e.preventDefault()}
function up(){if(!state.drag)return;state.moves++;$('#moves').textContent=state.moves;state.drag=null}
function unlock(k,r){if(k.off)return;k.off=true;r.rot=target(r,k);play('release',.75);toast('榫位相合 · 金扣轻启');setTimeout(()=>{if(r.links.every(id=>state.clasps.find(q=>q.id===id)?.off))r.gone=true;if(!available().length&&state.clasps.every(k=>k.off))complete();else updateOracle()},320)}
function updateOracle(){let k=available()[0];if(!k)return;$('#oracleName').textContent=`${k.gua[0]} · ${k.dir===-1?'阴':k.dir===1?'阳':'和'}`;$('#oracleHint').textContent=`生门${k.gua[1]} · ${k.dir===-1?'逆势回旋':k.dir===1?'顺势而行':'循光而转'}`}
function complete(){let j=JEWELS[state.level];state.completed.add(state.level);save();play('done',.9);setTimeout(()=>{$('#completeTitle').textContent=`${j.name} · 收入藏宝阁`;$('#completeText').textContent=`第${toCN(state.level+1)}重天机已解，${j.gua}象归位。`;$('#finalMoves').textContent=state.moves;$('#finalTime').textContent=clock();$('#completeModal').classList.add('show')},650)}
function clock(){let s=Math.floor((Date.now()-state.start)/1000);return`${String(s/60|0).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}function toast(t){let n=$('#toast');n.textContent=t;n.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>n.classList.remove('show'),1100)}function play(id,v=1){if(!state.sound)return;let a=$('#'+id);try{a.currentTime=0;a.volume=v;a.play().catch(()=>{})}catch{}}
$('#continueBtn').onclick=()=>openGame(last());$('#treasuryBtn').onclick=()=>{buildTreasury();setScreen('treasuryScreen')};$('#treasuryBack').onclick=()=>setScreen('homeScreen');$('#gameExit').onclick=()=>{buildTreasury();setScreen('treasuryScreen')};$('#settingsBtn').onclick=()=>$('#settingsModal').classList.add('show');$('#settingsClose').onclick=$('#settingsDone').onclick=()=>$('#settingsModal').classList.remove('show');$('#musicToggle').checked=state.sound;$('#easyToggle').checked=state.easy;$('#musicToggle').onchange=e=>{state.sound=e.target.checked;localStorage.setItem('yh-sound',state.sound);if(!state.sound)$('#bgm').pause()};$('#easyToggle').onchange=e=>{state.easy=e.target.checked;localStorage.setItem('yh-easy',state.easy)};
$('#hint').onclick=()=>{if(!state.hints)return toast('提示已经用完啦');state.hints--;$('#hints').textContent=state.hints;let k=available()[0],r=k&&ringBy(k.pair[0]);if(k&&r){r.rot=target(r,k)+(k.dir===-1?-.48:.48);updateOracle();toast(`${k.gua[0]}位生门已显，再轻轻${k.dir===-1?'逆':'顺'}转`)}};$('#reset').onclick=()=>openGame(state.level);$('#sound').onclick=()=>$('#musicToggle').click();$('#nextLevel').onclick=()=>{$('#completeModal').classList.remove('show');if(state.level<29)openGame(state.level+1);else{buildTreasury();setScreen('treasuryScreen')}};
c.onpointerdown=down;c.onpointermove=move;c.onpointerup=up;c.onpointercancel=up;setInterval(()=>{if($('#gameScreen').classList.contains('active'))$('#time').textContent=clock()},1000);document.addEventListener('pointerdown',()=>{if(state.sound){let a=$('#bgm');a.volume=.13;a.play().catch(()=>{})}},{once:true});buildHome();buildTreasury();frame();})();
